[tox]
skipsdist = true
envlist = lint, type, test
skip_missing_interpreters = true

[testenv]
basepython = python3.11
setenv =
    PYTHONPATH = {toxinidir}

[testenv:lint]
basepython = python3.11
deps =
    black>=24.4.0
    flake8>=7.0.0
    isort>=5.13.0
commands =
    black --check {posargs:.}
    isort --check {posargs:.}
    flake8 {posargs:lou_op/}

[testenv:type]
basepython = python3.11
deps =
    mypy>=1.9.0
    types-PyYAML>=6.0.0
commands =
    mypy --show-error-codes --config-file {toxinidir}/pyproject.toml \
        {posargs:lou_op/}

[testenv:test]
basepython = python3.11
deps =
    pytest>=8.0.0
commands =
    pytest {posargs:tests/}
